### ISSUE TITLE
Array root behavior results in less dry code

### ISSUE THREAD

**Issue by sethherr** [jrhe/grape-active_model_serializers#41]
What is the reason for not using the serializer's root if it's set? 

It seems to me like that should be the expected behavior. If you set a ` self.root = "XXX"` in your serializer, that is the root for the array, and that can only be overridden by the root in grape itself.

I can submit a pull request with the change if there isn't a specific reason you've chosen not to implement that pattern.

**Comment by siong1987** [comment]
i don't really understand what is the pattern you are talking about here?  code snippets?

**Comment by sethherr** [comment]
Sorry, this apparently is no longer a feature of active_model_serializers. My bad!
