### ISSUE TITLE
how to use helpers to conditionally include an attribute?

### ISSUE THREAD

**Issue by mepatterson** [jrhe/grape-active_model_serializers#42]
I'm confused on how to go about what I'm trying to do. Seems like it should be easy.

I'm building an API that doesn't have users, but it does have _applications_ that connect to it via OAuth.

I have a grape endpoint:
```ruby
desc "Get widgets"
get '/' do
  @widgets = Widget.all
  @widgets
end
```
I have a serializer:
```ruby
class WidgetSerializer < ActiveModel::Serializer
  attributes :name, :color
end
```
I have a helper:
```ruby
module ApplicationHelpers
  def current_application
    # returns an AuthorizedApplication object based on the current authentication
  end
end
```
What I _want_ to do is have my WidgetSerializer conditionally include a `secret_number` attribute in the JSON _only_ for applications with the proper role (e.g. `current_application.has_role?(:fullaccess)`)
```ruby
# this doesn't work, obviously
class WidgetSerializer < ActiveModel::Serializer
  attributes :name, :color
  attributes :secret_number if current_application.has_role?(:fullaccess)
end
```
What am I missing? I've tried a bunch of things online and none seem to work. What's the correct way to do this with grape-active_model_serializers?

Thanks for your help...

**Comment by siong1987** [comment]
check this out: http://railscasts.com/episodes/409-active-model-serializers?view=asciicast

see how they use `current_user` in serializer.

**Comment by mepatterson** [comment]
So I saw that rails cast and I've tried every permutation of serialization_scope and scope and creating an attributes override method in my serializer class. None of it seems to do anything at all. Maybe I'm missing some secret step with grape+ams? This rails cast is for ams in a rails controller. Is there something special I have to do to make it work in grape?

—
Matt E. Patterson
http://mepatterson.net
http://amzn.to/mepatt

**Comment by mepatterson** [comment]
UPDATE: So I think I figured it out.  I had to do this _inside_ my endpoint block:

```ruby
desc "Get widgets"
get '/' do
  _serialization_scope = :current_application
  @widgets = Widget.all
  @widgets
end
```

This is less than optimal, since I'll have to constantly do this in every endpoint I define. :( But I guess it works. Would be nice if there was a more straightforward way to allow a serializer access to a grape helper.

**Comment by siong1987** [comment]
cool.  i am closing this issue now since you already figure it out  :)
