### ISSUE TITLE
can't use ActiveModel::SerializableResource

### ISSUE THREAD

**Issue by xiaok** [jrhe/grape-active_model_serializers#44]
ActiveModel::SerializableResource.new(@user)

error: 
uninitialized constant ActiveModel::SerializableResource

**Comment by dblock** [comment]
If you have a project up I can try to help you. This is most likely a missing `require`.

**Comment by xiaok** [comment]
solved

**Comment by dblock** [comment]
@xiaok Care to elaborate?

**Comment by twetzel** [comment]
same Problem! .. how to fix ?

**Comment by shanet** [comment]
I had `gem 'active_model_serializers'` in my Gemfile which was using a version without this class in it (`0.9.3`). Specifying the latest release (`0.10.0.rc3`) fixed it: `gem 'active_model_serializers', '>= 0.10.0.rc3'`

**Comment by xiaok** [comment]
@dblock @twetzel 
I use ```ActiveModel::Serializer.serializer_for(model).new(model).serializable_hash``` instead.
but this function can not use current_user
