### ISSUE TITLE
'current_user'  helper can't be accessed from serializers

### ISSUE THREAD

**Issue by xiaok** [jrhe/grape-active_model_serializers#45]
as example said https://github.com/jrhe/grape-active_model_serializers#current_user

grape_helper.rb : 

``` 
def current_user
  @current_user ||= UserSession.create(User.find_by({access_token: params[:token]}, false)).user
end
```

grape module : 
```
get ':id/works' do
    generate_mate_and_array Model.find(params[:id])
end
```

serializer.rb
```
attributes :id, :user
def user
    current_user
end
```

But when I call this api, caused an error : " undefined method current_user "

add delegate in baseSerializer

```
  delegate :current_user, to: :scope
```

caused an error too " BaseSerializer#current_user delegated to scope.current_user, but scope is nil ".

How can I use current_user in serializer ?

**Comment by xiaok** [comment]
sry, my fault

**Comment by dblock** [comment]
@xiaok Care to elaborate for the next person having this issue?

**Comment by xiaok** [comment]
I use a funtion to render json

```
def generate_json(model)
      ActiveModel::Serializer.serializer_for(model).new(model).serializable_hash
end

def generate_array(model)
    ActiveModel::Serializer.serializer_for(model).new(model)
end
```

and those functions can not read current_user
